#!/bin/bash
if [[ -z $1 ]]; then
	file=$(fzf --preview 'bat --style=numbers --color=always --line-range :500 {}')
	newFile=$(echo $file|sed "s/md/odt/")
	pandoc -f markdown -t odt $file -o $newFile
else
	newFile=$(echo $1|sed "s/md/odt/")
	pandoc -f markdown -t odt $1 -o $newFile
fi
libreoffice --view $newFile
